// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSrBDeEDxyeNoix0Ub_I2g1JOXBrqeoOc',
    appId: '1:1003991374433:web:a9fb909ae5d45a7b88e820',
    messagingSenderId: '1003991374433',
    projectId: 'task-final-e36f8',
    authDomain: 'task-final-e36f8.firebaseapp.com',
    storageBucket: 'task-final-e36f8.firebasestorage.app',
    measurementId: 'G-B31BGYYDL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1_4bCST0FaktouTjMoSBwYv2riQJRVAs',
    appId: '1:1003991374433:android:38f4ff9f57c081d388e820',
    messagingSenderId: '1003991374433',
    projectId: 'task-final-e36f8',
    storageBucket: 'task-final-e36f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBER8ZqvSMCGE-ksZJRnqWNfLGac2G5z_A',
    appId: '1:1003991374433:ios:a6bb1e89a7f643f588e820',
    messagingSenderId: '1003991374433',
    projectId: 'task-final-e36f8',
    storageBucket: 'task-final-e36f8.firebasestorage.app',
    iosBundleId: 'com.example.taskFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBER8ZqvSMCGE-ksZJRnqWNfLGac2G5z_A',
    appId: '1:1003991374433:ios:a6bb1e89a7f643f588e820',
    messagingSenderId: '1003991374433',
    projectId: 'task-final-e36f8',
    storageBucket: 'task-final-e36f8.firebasestorage.app',
    iosBundleId: 'com.example.taskFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSrBDeEDxyeNoix0Ub_I2g1JOXBrqeoOc',
    appId: '1:1003991374433:web:7831b62cda7a49f788e820',
    messagingSenderId: '1003991374433',
    projectId: 'task-final-e36f8',
    authDomain: 'task-final-e36f8.firebaseapp.com',
    storageBucket: 'task-final-e36f8.firebasestorage.app',
    measurementId: 'G-YZFEPLQKH9',
  );
}
